// src/app/shorts/page.tsx
import { getArticles } from "@/lib/db";
import ShortsClient from "./ShortsClient";

export const revalidate = 60;

export default async function ShortsPage() {
  const { articles } = await getArticles({ status: "PUBLISHED", pageSize: 30 });

  const shorts = articles
    .filter((a) => a.imageUrl)
    .concat(articles.filter((a) => !a.imageUrl))
    .slice(0, 30)
    .map((a) => ({
      id:            a.id,
      slug:          a.slug,
      title:         a.title,
      // shortNews field from Firestore (generated by scraper)
      // fallback to excerpt only if shortNews is missing
      shortNews:     (a as any).shortNews || (a as any).shortContent || a.excerpt,
      imageUrl:      a.imageUrl || null,
      categoryName:  a.categoryName,
      categorySlug:  a.categorySlug,
      categoryColor: a.categoryColor,
      views:         a.views,
      publishedAt:   a.publishedAt?.toISOString() || a.createdAt.toISOString(),
    }));

  return <ShortsClient shorts={shorts} />;
}
